### ISSUE TITLE
Change font size?

### ISSUE THREAD

**Issue by ghost** [mike-eason/WPF_ToastNotifications#1]
Hi there,
I can see we can change fontfamily, but what about size for both the title and message body?
Thanks

**Comment by ghost** [comment]
Hi,
Sorry, I can't get your styling example to work either (just changing fontfamily). The style seems to be ignored.
I'm putting it in my mainwindow resources.

Any help appreciated.

Thank you

**Comment by dazzalogan** [comment]
Hi,
Sorry, I can't get your styling example to work either (just changing fontfamily). The style seems to be ignored.
I'm putting it in my mainwindow resources.

Any help appreciated.

Thank you

**Comment by mike-eason** [comment]
Hi there,

Please can you share your code so I can debug? I haven't used WPF for a couple of years now but I'll give it a go.

**Comment by ghost** [comment]
Hi Mike,
Thanks for quick response.

Really I'd like to see your example working, but it doesn't seem to.

This:

xmlns:toast="clr-namespace:PeanutButter.Toast;assembly=PeanutButter.Toast"

...

<Style TargetType="{x:Type toast:ToastNotification}" BasedOn="{StaticResource {x:Type toast:ToastNotification}}">
   <Setter Property="FontFamily" Value="Consolas"/>
   ...
</Style>


I don't see any change to the font. It seems to be ignored.

Please could you try your own example again?

I'm using VS 2012 Pro. / VB.net.

Thank you

Regards,
Darren

**Comment by dazzalogan** [comment]
`xmlns:toast="clr-namespace:PeanutButter.Toast;assembly=PeanutButter.Toast"

...

<Style TargetType="{x:Type toast:ToastNotification}" BasedOn="{StaticResource {x:Type toast:ToastNotification}}">
   <Setter Property="FontFamily" Value="Consolas"/>
   ...
</Style>`
